### ISSUE TITLE
`backdropStyles` on final modal overrides all modals if multiple used on single page

### ISSUE THREAD

**Issue by AshSimmonds** [Alaricus/solid-dialog#1]
Both pics are the second of multiple modals. First pic is with no blur modifiers. Second pic is with `backdropStyles={{ 'backdrop-filter': 'blur(30px)', }}` set on the final modal.

![screenshot_20230119-164957_msedge_l03rHuB1lV](https://user-images.githubusercontent.com/9034041/213370429-371092ca-ada4-4dfd-9a92-904a83dd9bf8.png)

![screenshot_20230119-165033_msedge_47BEY1SSbD](https://user-images.githubusercontent.com/9034041/213370472-87261878-9403-422a-ba8c-07eed13e9c55.png)

**Comment by Alaricus** [comment]
I believe this behavior is inherent to the `<dialog>` tag. Each dialog has its own backdrop, which is independent of any underlying backdrops. Its effects and colors will be displayed on top of anything that's already displayed, so it's not that it overrides the previous ones, it's that it compounds them by being layered on top of them.

Here is a vanilla JS example I made: https://codesandbox.io/s/crimson-dream-wve31k?file=/index.html

There `dialog1` has a red translucent backdrop and `dialog2` has a blue translucent one. When you display both modals the backdrops become purple due to the red and the blue mixing together. It seems that these native modals were not really meant to be used several at a time.
